version: "3"

services:
  web:
    build: ./Web
    networks:
      - piast-net
    ports:
      - '5000:5000'

  api:
    build: ./Api
    networks:
      - piast-net
    ports:
      - '5001:5000'
  
  mongodb:
    image: mongo:3.2.20-jessie
    networks:
      - piast-net
    ports:
      - '27017:27017'


networks:
  piast-net:
    driver: bridge